# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...
    - name: Build darwin-arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o data-bundle-tracker-darwin-arm64 data-bundle-tracker.go
    - name: Build windows-amd64
      run: env GOOS=windows GOARCH=amd64 go build -o data-bundle-tracker-windows-amd64.exe data-bundle-tracker.go

    - name: Test
      run: go test -v ./...

    - name: Pack release files
      run: |
        zip --junk-paths data-bundle-tracker data-bundle-tracker-darwin-arm64 data-bundle-tracker-windows-amd64.exe README.md

    - name: Compute the release tag
      run: |
        echo "release_tag=v`date '+%Y-%m-%d'`" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ env.release_tag }}
        # target_commitish: main
        files: data-bundle-tracker.zip
